# Generated by Django 6.0.1 on 2026-01-17 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(help_text='e.g. app.example.com', max_length=200)),
                ('repo_url', models.CharField(help_text='https://github.com/user/repo', max_length=300)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('port', models.IntegerField(help_text='Internal Gunicorn port (e.g. 8000)', unique=True)),
                ('python_version', models.CharField(default='3.11', max_length=10)),
                ('env_vars', models.TextField(blank=True, help_text='KEY=VALUE (one per line)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('logs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='panel.project')),
            ],
        ),
    ]
